---
exclude:
  - "70668"
include:
  - "77715":
      scene:
        absolute: 2
        season: 54
        episode: 2
      tvdb:
        absolute: 1
        season: 52
        episode: 1
      range: 300
      names:
        - Emmerdale: 52
