---
exclude:
  - "72241"
  - "12345"
include:
  - "326732":
      scene:
        absolute: 1
        season: 1
        episode: 1
      tvdb:
        absolute: 1
        season: 1
        episode: 1
      names:
        - Name 1: -1
        - Name 2: -1
  - "999999":
      names:
        - Example All Seasons Title 1: -1
        - Example All Seasons Title 2: -1
        - Example Season 1 Title: 1
        - Example Season 2 Title: 2
        - Example Season 3 Title: 3
